fix(compiler-web): 修复编译slot组件的slot属性失败问题
eleme/morjs pull request #219
Opened 2024-09-04 06:27 UTC by williamyuanjw

2024-09-04 09:21 UTC, aboyforwind approved these changes

2024-09-04 09:45 UTC, aboyforwind reviewed
具体修复的问题发说一下哪

2024-09-04 09:49 UTC, aboyforwind requested changes
具体修复的问题说一下哪

2024-09-04 12:16 UTC, williamyuanjw commented
> 具体修复的问题说一下哪
子组件有一个slot标签 接受孙子组件传过来对应的插槽内容 再通过子组件slot标签传给父组件
这个写法原生支付宝小程序没问题 但是原生支付宝小程序编译成web端有问题
![image](https://github.com/user-attachments/assets/8be1d015-cd90-4463-855a-15f93c47dcd4)
![image](https://github.com/user-attachments/assets/c7875717-8b1c-4a5c-9887-5143cf1c0b5a)

2025-03-24 06:43 UTC, aboyforwind approved these changes

2025-03-24 06:43 UTC, merged